dist: bionic
sudo: required

# Enable C++ support
language: cpp

# Compiler selection
compiler: gcc

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "BI/LipviGMg5vmQM3G1ZMUksOa8TDJWbyR/5BV6P1xQuv152LLbhXacX/wlxNaPfmFshhi6x9UwYbJ/TQCAfVi1vEIlGinDxAW9OUWVgCNsC0ipw1wI0ro+wGuSahGm3k58Y2jUMKgi22RNfyNTPmAlDA4uBaIZvSU6sah75EUv9lQOIsB+uS9i16JkAbAjfE/cdZtW1upJN3vA+b8FhItg4d8jGadVMrnCgkf7Gna6Oo4z3m8KFuGZKY5HrbcpM0ty7zV+0f44s92O4AYKzUnYwE7uaqORv2RF/2W8a4zirIFsbzaHgGsRMyxt/vktL1Nkk2IhK/fsSLjFDao0kGUnLkCfcx1icO6t4pSgxgnsl0n9p4M8dSibG2RYDo5sqU0B7a/mgUIVWUXTniYZOFA93eIA/JMgkdI1KTMInwzDLjygqILbLoS3tiirkB4ElHk4YUaLgKpRiN9V5wg+Beeittq6KIqAzWXoesDAN4KVEvc9NRUFGxb5rWaRmMYJKPhXXIS5iZivSmYcOgl9Hade31s0EehIsi4YvHVThxeg/zAqXFGof3bIId9r/77r3nIKVkZhhbbd8g/jR1SxH2AJEMWpLIfzgiDvG0LwIzdbNeee1xGQsTGV17XL/c/FaBm9CVCRp3iAj4KgNF8+CAkojATVEl4YBl6JUMiNFykw="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "RespiraWorks/printf"
      description: "Printf for ventilator debug interface"
    notification_email: martin@respira.works
    build_command_prepend: "make clean"
    build_command: "make"
    branch_pattern: coverity_scan

script:
  # Check versions of gcc, g++
  - gcc -v && g++ -v
  # Run build commands
  - make
  # execute the text suite
  - bin/test_suite -d yes
  # coverall profiling
  - tmp/cov/test_suite

after_success:
  ## Report to codecov
  - bash <(curl -s https://codecov.io/bash)

